apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tuf5se3v7-java-springboot
  janus-idp.io/tekton: tuf5se3v7-java-springboot
  backstage.io/kubernetes-id: tuf5se3v7-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tuf5se3v7-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
